# Generated by Django 4.2.7 on 2023-12-06 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=250)),
                ('contexte', models.TextField()),
                ('problematique', models.TextField()),
                ('objectifs', models.TextField()),
                ('resultats', models.TextField()),
                ('planing', models.TextField()),
                ('nom_entreprise', models.CharField(max_length=250)),
                ('statut', models.BooleanField()),
                ('cote', models.CharField(max_length=250)),
                ('tags', models.CharField(max_length=250)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='memoires/')),
                ('annee', models.IntegerField(default=2023)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('directeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directeur', to='memo.enseignant')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auteur', to='memo.etudiant')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
