# Generated by Django 4.2.8 on 2024-01-16 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoire',
            name='est_public',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='specialite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='memo.specialite'),
        ),
    ]
