# Generated by Django 4.2.7 on 2023-12-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0003_alter_utilisateur_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_naiss',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
