# Generated by Django 4.2.7 on 2023-12-06 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0004_alter_utilisateur_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoire',
            name='utilisateur',
        ),
        migrations.AlterField(
            model_name='memoire',
            name='cote',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='directeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directeur', to='memo.enseignant'),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='nom_entreprise',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='planing',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='statut',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='tags',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
