# Generated by Django 4.2.7 on 2023-12-06 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0005_remove_memoire_utilisateur_alter_memoire_cote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoire',
            name='cote',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='directeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directeur', to='memo.enseignant'),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='nom_entreprise',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='planing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='tags',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
